version: "3.9"

services:
  spring-bot:
    image: 701804429993.dkr.ecr.eu-north-1.amazonaws.com/andreibel/spring-bot:latest
    container_name: spring-bot
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - secret.env